files:
  # define files included in the analysis (defaults to ["{app,lib}/**/*.rb"])
  included:
    - src/**/*.ts
  # define files excluded from the analysis (defaults to [])
  excluded:
    - *.d.ts